# Generated by Django 2.2.5 on 2020-08-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=75)),
                ('why_here', models.CharField(max_length=200)),
                ('date_saved', models.DateField()),
                ('rate_city', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
        ),
    ]
