# Generated by Django 2.2.5 on 2020-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeachApp', '0002_auto_20200821_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecities',
            name='rate_city',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=100),
        ),
    ]
