# Generated by Django 2.2.5 on 2020-08-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeachApp', '0006_auto_20200828_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecities',
            name='rate_city',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=75),
        ),
    ]
